import * as Bootstrap from 'react-bootstrap';
import * as Router from 'react-router';
export declare const Pagination: __React.ClassicComponentClass<Bootstrap.PaginationProps>;
export declare const Grid: __React.ClassicComponentClass<Bootstrap.GridProps>;
export declare const Row: __React.ClassicComponentClass<Bootstrap.RowProps>;
export declare const Col: __React.ClassicComponentClass<Bootstrap.ColProps>;
export declare const FontAwesome: any;
export declare const Link: typeof Router.Link;
export declare const Alert: __React.ClassicComponentClass<Bootstrap.AlertProps>;
export declare const Button: __React.ClassicComponentClass<Bootstrap.ButtonProps>;
export declare const FormControl: Bootstrap.FormControlClass;
export declare const Form: typeof Bootstrap.Form;
export declare const Panel: __React.ClassicComponentClass<Bootstrap.PanelProps>;
export declare const FormGroup: typeof Bootstrap.FormGroup;
export declare const Modal: Bootstrap.ModalClass;
export declare const ControlLabel: typeof Bootstrap.ControlLabel;
export declare const ButtonGroup: __React.ClassicComponentClass<Bootstrap.ButtonGroupProps>;
export declare const Checkbox: typeof Bootstrap.Checkbox;
export declare const Tabs: __React.ClassicComponentClass<Bootstrap.TabsProps>;
export declare const Tab: Bootstrap.TabClass;
export declare const Radio: typeof Bootstrap.Radio;
export declare const Input: typeof Bootstrap.Input;
export declare const Label: typeof Bootstrap.Label;
export declare const Well: typeof Bootstrap.Well;
export declare const Table: __React.ClassicComponentClass<Bootstrap.TableProps>;
export declare const Tooltip: __React.ClassicComponentClass<Bootstrap.TooltipProps>;
export declare const OverlayTrigger: __React.ClassicComponentClass<Bootstrap.OverlayTriggerProps>;
