export declare const SAVE_INSTANCE: string;
export declare const UPDATE_INSTANCE: string;
export declare const DELETE_INSTANCE: string;
export declare const SAVE_ALL_INSTANCES: string;
export declare const FETCH_INSTANCE_DATA: string;
export declare const FETCH_INSTANCE_LIST: string;
export declare const FETCH_INSTANCE_DATA_START: string;
export declare const FETCH_INSTANCE_DATA_FULFILLED: string;
export declare const FETCH_INSTANCE_DATA_ERROR: string;
export declare const FETCH_INSTANCE_LIST_START: string;
export declare const FETCH_INSTANCE_LIST_FULFILLED: string;
export declare const FETCH_INSTANCE_LIST_ERROR: string;
export declare const SET_PAGE: string;
export declare const UNSET_RESOURCE_LIST: string;
export declare const TOGGLE_FILTERS: string;
export declare const TOGGLE_NAV: string;
export declare const MISSING_ACTION_PAYLOAD: string;
export declare const INVALID_COMMAND_ERROR: (...optionNames: string[]) => string;
export declare const INVALID_MODEL_NAME: (modelName: string, modelPath: string) => string;
export declare const MISSING_PARAMETER: (paramName: string, functionName: string) => string;
export declare const NO_PROP_TYPES: (modelName: string) => string;
export declare const NO_DEFAULT_PROPS: (modelName: string) => string;
export declare const PAGE_NOT_FOUND: string;
export declare const INSTANCE_NOT_FOUND: string;
export declare const INSTANTIATION_ERROR: string;
export declare const INVALID_STATE: string;
export declare const RESOURCE_DATA_UNINTIALIZED: (resource: string) => string;
export declare const INVALID_INSTANCE: string;
export declare const MODEL_RESOURCE_ERROR: string;
export declare const MISSING_ID_IN_METHOD: (methodName: string) => string;
